CREATE TABLE ACCOUNTS (
USER_ID VARCHAR(10)  PRIMARY KEY, 
PASS   VARCHAR(100)  NOT NULL, 
MAIL   VARCHAR(100) NOT NULL,
NAME   VARCHAR(40)  NOT NULL,
AGE    INT          NOT NULL
);

CREATE TABLE PRODUCTS (
PRODUCT_ID   VARCHAR(255) PRIMARY KEY,
PRODUCT_NAME VARCHAR(255),
PRODUCT_DESCRIBE VARCHAR(1024),
IMG_URL   VARCHAR(255),
PRICE       INT
);

CREATE TABLE ORDERS (
ORDER_ID   INT PRIMARY KEY AUTO_INCREMENT,
USER_ID VARCHAR(10),
PRICE       INT
);

CREATE TABLE ORDERITEMS (
ORDER_ITEM_ID  INT PRIMARY KEY AUTO_INCREMENT,
ORDER_ID INT,
PRODUCT_ID   VARCHAR(255),
QUANTITY       INT
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIBE, IMG_URL, PRICE) VALUES ('P001', 'Product A','商品Aの説明文', 'java.jpg', 1000);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIBE, IMG_URL, PRICE) VALUES ('P002', 'Product B','商品Bの説明文', 'sql.jpg', 1500);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIBE, IMG_URL, PRICE) VALUES ('P003', 'Product C','商品Cの説明文', 'servlet.jpg', 2500);
